---

- name: create laravel db app
  mysql_db:
    name: LaravelApp
    state: present

- name: Configure and copy the env file
  template:
    src: .env
    dest: "{{remote_www_root }}/{{app_path}}/"

  
- name: Install laravel
  become: false
  composer:
    command: install
    working_dir: "{{remote_www_root}}/{{ app_path }}"
  tags: ['composer:install']
  ignore_errors: yes

- name: Generate key
  command: "/usr/bin/php {{remote_www_root}}/{{app_path}}/"
  tags: ['laravel', 'artisan:key']

- name: Storage set up
  command: "/usr/bin/php {{remote_www_root}}/{{app_path}}/"
  tags: ['laravel', 'artisan:storage'] 

- name: Run migrations
  command: "/usr/bin/php {{remote_www_root}}/{{app_path}}/"
  tags: ['laravel', 'artisan:migrate'] 
