---
- name: Setup and clone project repo
  git:
    dest: "{{ remote_www_root}}//{{ app_root}}"
    repo: "{{git_repo}}"


- name: Remote app root and right permission
  file:
    path: "{{ remote_www_root}}//{{ app_root }}"
    state: directory
    mode: '0755'
    owner: "{{ remote_user}}"
    group: "{{ remote_user}}"

- name: Setting up permission and directory for ww-data
  file:
    path: "{{ remote_www_root }}//{{app_root}}//bootstrap/cache"
    state: directory
    mode: 0777
    owner: "{{remote_user}}"

- name: Setting up permission and directory for www-data on stroage
  file:
    path: "{{remote_www_root}}//{{app_root}}/storage/logs/laravel.log"
    mode: 0777
    owner: "{{ remote_user }}"
    state: directory
