---
- name: Setup and clone project repo
  git:
    dest: "{{ remote_www_root}}//{{ app_root_dir}}"
    repo: "{{git_repo_url}}"


- name: Remote app root and right permission
  file:
    path: "{{ remote_www_root}}//{{ app_root_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ remote_user}}"
    group: "{{ remote_user}}"

- name: 
